// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymu8PRjx8zKaqLp1gjj7KE1AIMKIF5Jc',
    appId: '1:872773517760:web:15849ab209a7384160c825',
    messagingSenderId: '872773517760',
    projectId: 'edu-lense-2026',
    authDomain: 'edu-lense-2026.firebaseapp.com',
    storageBucket: 'edu-lense-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT88A2I_7OhogYrRMj9uxsVx-pXG_nktc',
    appId: '1:872773517760:android:a15631084ea1c0e260c825',
    messagingSenderId: '872773517760',
    projectId: 'edu-lense-2026',
    storageBucket: 'edu-lense-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZFA5l1mqrOkBX4A-Ucff4yRZ4nGJObJM',
    appId: '1:872773517760:ios:1cfdc11008a4138660c825',
    messagingSenderId: '872773517760',
    projectId: 'edu-lense-2026',
    storageBucket: 'edu-lense-2026.firebasestorage.app',
    iosBundleId: 'com.example.learninglensApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZFA5l1mqrOkBX4A-Ucff4yRZ4nGJObJM',
    appId: '1:872773517760:ios:1cfdc11008a4138660c825',
    messagingSenderId: '872773517760',
    projectId: 'edu-lense-2026',
    storageBucket: 'edu-lense-2026.firebasestorage.app',
    iosBundleId: 'com.example.learninglensApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAymu8PRjx8zKaqLp1gjj7KE1AIMKIF5Jc',
    appId: '1:872773517760:web:4437405e130e8f3c60c825',
    messagingSenderId: '872773517760',
    projectId: 'edu-lense-2026',
    authDomain: 'edu-lense-2026.firebaseapp.com',
    storageBucket: 'edu-lense-2026.firebasestorage.app',
  );
}
